### ISSUE TITLE
Time zone objects don't unpickle sanely

### ISSUE THREAD

**Issue by akaihola** [gweis/isodate#28]
```
>>> isodate.UTC == pickle.loads(pickle.dumps(isodate.UTC))
False
```

This causes headache when unpickling a data structure which contains time zone objects. For example Pandas Timestamp subtraction fails when one of the timestamps is constructed in code and the other comes from a pickle:

```
Traceback (most recent call last):
  File "test.py", line 10, in test
    duration = end - begin
  File "pandas/tslib.pyx", line 946, in pandas.tslib._Timestamp.__sub__ (pandas/tslib.c:17476)
TypeError: Timestamp subtraction must have the same timezones or no timezones
```

Our work-around is to switch from `isodate.UTC` to `pytz.utc`:

```
>>> pytz.utc == pickle.loads(pickle.dumps(pytz.utc))
True
```

**Comment by gweis** [comment]
thanks
