### ISSUE TITLE
isodate 0.7.0 release incorrectly fetched on python 2 systems

### ISSUE THREAD

**Issue by fervand1** [gweis/isodate#91]
The new release 0.7.0 is failing python 2 pipelines. The version is incorrectly fetched when it should not be compatible on python 2 systems at all. Following issue is logged in the CI pipelines
```
Collecting isodate
  Downloading isodate-0.7.0.tar.gz (29 kB)
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
  WARNING: Generating metadata for package isodate produced metadata for project name unknown. Fix your #egg=isodate fragments.
ERROR: Exception:
Traceback (most recent call last):
  File "/builds/venv_tmp/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/builds/venv_tmp/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/builds/venv_tmp/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 321, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/builds/venv_tmp/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 180, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/builds/venv_tmp/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 419, in _resolve_one
    assert req_to_install.user_supplied
AssertionError
```
Quick fix for the solution is to pin the lower versions where ever it is used but would be better if the newer version is rectified with correct markers

**Comment by estan** [comment]
We are also hitting this. Would be great with re-upload of a fixed 0.7.0, to avoid people like us who still have to support EOLed Python 2 having to pin back to `<=0.7.0` (isodate is just a transient dependency of ours).

**Comment by gweis** [comment]
Added `requires-python = ">=3.7"` to the metadata , which should fix your issue.

**Comment by fervand1** [comment]
Thanks @gweis
